GET http://localhost:3000/variables HTTP/1.1
###
PATCH http://localhost:3000/vendedor/220 HTTP/1.1
Content-Type: application/json

{
"name" : "noNPC4",
"email" : "antiNPC2@gmail.com",
"phone" : "00000009"
}
###
PATCH http://localhost:3000/variables/223 HTTP/1.1
Content-Type: application/json

{
    "name" : "holacuota"
}
###
PATCH http://localhost:3000/password/220 HTTP/1.1
Content-Type: application/json

{
    "password" : "yanoesunaloca..."
}
###
POST http://localhost:3000/variables HTTP/1.1
Content-Type: application/json

{
    "name" : "cuotaTomas",
    "cantidad" : 100
}